CREATE TABLE system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL,
    setting_value VARCHAR(500) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_system_settings_setting_key UNIQUE (setting_key)
);
