CREATE TABLE appointment_internal_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL REFERENCES appointments (id) ON DELETE CASCADE,
    author_username VARCHAR(100) NOT NULL,
    note VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_appointment_internal_notes_appointment_id ON appointment_internal_notes (appointment_id);

INSERT INTO appointment_internal_notes (appointment_id, author_username, note, created_at)
SELECT id, 'legacy', internal_notes, CURRENT_TIMESTAMP
FROM appointments
WHERE internal_notes IS NOT NULL AND TRIM(internal_notes) <> '';

ALTER TABLE appointments DROP COLUMN internal_notes;
